In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd

In [3]:
iris= load_iris()

In [4]:
target=iris['target']

In [5]:
import numpy as np

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
from sklearn.svm import SVC

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
from sklearn.model_selection import cross_val_score

In [18]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=5)

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [36]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [31]:
cross_val_score(RandomForestClassifier(n_estimators=100),iris.data,iris.target,cv=5)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [38]:
cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=10)

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.86666667, 0.93333333, 1.        , 1.        , 1.        ])